import { createServer, IncomingMessage, ServerResponse } from "node:http";
import { spawn } from "node:child_process";
import { AddressInfo } from "node:net";
import { BridgeCredentials, saveCredentials } from "./credentials.js";

const FORM_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Proton Drafts MCP — Setup</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; background: #1b1340; color: #eee; max-width: 520px; margin: 40px auto; padding: 0 20px; }
  h1 { color: #8a7cff; }
  label { display: block; margin: 14px 0 4px; font-size: 14px; }
  input { width: 100%; padding: 10px; border: 1px solid #444; background: #2a205c; color: #eee; border-radius: 6px; font-size: 14px; box-sizing: border-box; }
  .row { display: flex; gap: 10px; }
  .row > div { flex: 1; }
  button { margin-top: 20px; padding: 12px 20px; background: #8a7cff; color: #111; border: none; border-radius: 6px; font-size: 15px; font-weight: 600; cursor: pointer; }
  button:hover { background: #a294ff; }
  small { color: #aaa; display: block; margin-top: 4px; }
  .help { background: #2a205c; padding: 14px; border-radius: 6px; margin-top: 20px; font-size: 13px; line-height: 1.5; }
</style>
</head>
<body>
<h1>Proton Drafts MCP — Setup</h1>
<p>Enter your Proton Bridge IMAP credentials. Saved to Windows Credential Manager under <code>proton-drafts-mcp</code>.</p>
<div class="help">
  <strong>Where to find these:</strong> Open Proton Bridge → click your account → <em>Mailbox details</em>. Use the IMAP host/port, your Proton email as username, and the Bridge-generated password (NOT your Proton login password).
</div>
<form method="POST" action="/save">
  <label>IMAP Host</label>
  <input name="host" value="127.0.0.1" required />
  <div class="row">
    <div>
      <label>Port</label>
      <input name="port" type="number" value="1143" required />
    </div>
    <div>
      <label>TLS</label>
      <select name="secure" style="width:100%;padding:10px;background:#2a205c;color:#eee;border:1px solid #444;border-radius:6px;">
        <option value="false" selected>STARTTLS (default)</option>
        <option value="true">SSL/TLS</option>
      </select>
    </div>
  </div>
  <label>Username (Proton email)</label>
  <input name="user" type="email" required placeholder="you@proton.me" />
  <label>Bridge password</label>
  <input name="password" type="password" required />
  <small>Auto-generated by Proton Bridge. Not your login password.</small>
  <button type="submit">Save & Continue</button>
</form>
</body>
</html>`;

const SUCCESS_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><title>Saved</title>
<style>body{font-family:sans-serif;background:#1b1340;color:#eee;text-align:center;padding:80px 20px;}h1{color:#8a7cff;}</style>
</head><body><h1>Credentials saved</h1><p>You can close this tab. The MCP server is starting.</p></body></html>`;

function parseForm(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const pair of body.split("&")) {
    const [k, v] = pair.split("=");
    if (k) out[decodeURIComponent(k)] = decodeURIComponent((v ?? "").replace(/\+/g, " "));
  }
  return out;
}

function openBrowser(url: string): void {
  if (process.platform === "win32") {
    spawn("cmd", ["/c", "start", "", url], { detached: true, stdio: "ignore" }).unref();
  } else if (process.platform === "darwin") {
    spawn("open", [url], { detached: true, stdio: "ignore" }).unref();
  } else {
    spawn("xdg-open", [url], { detached: true, stdio: "ignore" }).unref();
  }
}

export function runSetupFlow(): Promise<BridgeCredentials> {
  return new Promise((resolve, reject) => {
    const server = createServer((req: IncomingMessage, res: ServerResponse) => {
      if (req.method === "GET" && (req.url === "/" || req.url === "/index.html")) {
        res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
        res.end(FORM_HTML);
        return;
      }
      if (req.method === "POST" && req.url === "/save") {
        let body = "";
        req.on("data", (chunk) => (body += chunk));
        req.on("end", () => {
          try {
            const form = parseForm(body);
            const creds: BridgeCredentials = {
              host: form.host,
              port: parseInt(form.port, 10),
              user: form.user,
              password: form.password,
              secure: form.secure === "true",
            };
            if (!creds.host || !creds.user || !creds.password || !Number.isFinite(creds.port)) {
              res.writeHead(400, { "Content-Type": "text/plain" });
              res.end("Missing required fields");
              return;
            }
            saveCredentials(creds);
            res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
            res.end(SUCCESS_HTML);
            setTimeout(() => {
              server.close();
              resolve(creds);
            }, 500);
          } catch (err) {
            res.writeHead(500, { "Content-Type": "text/plain" });
            res.end("Failed to save: " + (err as Error).message);
            reject(err);
          }
        });
        return;
      }
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("Not Found");
    });

    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address() as AddressInfo;
      const url = `http://127.0.0.1:${addr.port}/`;
      process.stderr.write(`[proton-drafts-mcp] Setup required. Opening browser: ${url}\n`);
      openBrowser(url);
    });
  });
}
